// Standardized All-India IT & Engineering Taxonomy for Candidate Profiles & Recruiter Search

export const ALL_INDIA_IT_CITIES = [
    "Pune",
    "Bengaluru",
    "Hyderabad",
    "Mumbai",
    "Navi Mumbai",
    "Thane",
    "Gurugram (Gurgaon)",
    "Noida",
    "Delhi / NCR",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Gandhinagar (GIFT City)",
    "Indore",
    "Kochi",
    "Trivandrum (Thiruvananthapuram)",
    "Coimbatore",
    "Jaipur",
    "Chandigarh",
    "Mohali",
    "Nagpur",
    "Nashik",
    "Chhatrapati Sambhajinagar (Aurangabad)",
    "Kolhapur",
    "Solapur",
    "Sangli",
    "Surat",
    "Vadodara",
    "Bhubaneswar",
    "Visakhapatnam (Vizag)",
    "Vijayawada",
    "Mysuru",
    "Mangaluru",
    "Hubballi-Dharwad",
    "Madurai",
    "Tiruchirappalli",
    "Bhopal",
    "Lucknow",
    "Kanpur",
    "Dehradun",
    "Guwahati",
    "Raipur",
    "Ranchi",
    "Patna",
    "Goa (Panaji / Verna)",
    "Remote (All India)"
];

export const TOP_IT_COMPANIES_INDIA = [
    // Tier-1 IT Services & Consulting
    "Tata Consultancy Services (TCS)",
    "Infosys",
    "Wipro",
    "HCLTech",
    "Tech Mahindra",
    "Cognizant Technology Solutions",
    "Accenture India",
    "Capgemini",
    "LTIMindtree",
    "IBM India",
    // Mid-Tier & Pune / India Engineering Leaders
    "Persistent Systems",
    "Zensar Technologies",
    "KPIT Technologies",
    "Cybage Software",
    "Hexaware Technologies",
    "Mphasis",
    "Birlasoft",
    "Coforge",
    "Sasken Technologies",
    "Sonata Software",
    "Happiest Minds Technologies",
    "Mastek",
    "Yash Technologies",
    "globant India",
    "EPAM Systems",
    "Publicis Sapient",
    "Nagarro",
    "Thoughtworks",
    "Synechron",
    "Virtusa",
    "HTC Global Services",
    // Global Tech Giants & Product Companies
    "Google India",
    "Microsoft India",
    "Amazon Development Centre",
    "Apple India",
    "Meta",
    "Netflix",
    "Oracle India",
    "SAP Labs India",
    "Cisco Systems",
    "Salesforce India",
    "Adobe India",
    "VMware (Broadcom)",
    "Atlassian",
    "ServiceNow",
    "Workday",
    "Intuit India",
    "PayPal India",
    "Uber India",
    "Stripe",
    "LinkedIn India",
    "NVIDIA",
    "Intel Technology India",
    "Qualcomm India",
    "AMD India",
    "Dell Technologies",
    "HP Enterprise (HPE)",
    "Red Hat India (IBM)",
    // Indian Unicorns, FinTech & Product Startups
    "Flipkart",
    "Jio Platforms",
    "Paytm",
    "PhonePe",
    "Razorpay",
    "Zerodha",
    "Groww",
    "CRED",
    "Postman",
    "Zoho Corporation",
    "Freshworks",
    "BrowserStack",
    "Swiggy",
    "Zomato",
    "Meesho",
    "Ola Electric / Ola",
    "MakeMyTrip",
    "Nykaa",
    "Dream11",
    "Juspay",
    "Pine Labs",
    "BharatPe",
    "Chargebee",
    "CleverTap",
    "Darwinbox",
    "Druva Data Solutions",
    "Icertis",
    "PubMatic",
    "Quick Heal (Seqrite)",
    "Gupshup",
    "Unacademy",
    "PhysicsWallah",
    // Big 4 & Global Banking / FinTech GCCs
    "Deloitte USI / India",
    "PwC India",
    "EY (Ernst & Young) GDS",
    "KPMG India",
    "ZS Associates",
    "Mastercard Technology",
    "Visa Inc.",
    "American Express",
    "JP Morgan Chase & Co.",
    "Goldman Sachs",
    "Morgan Stanley",
    "Barclays Global Service Centre",
    "Citi (Citicorp Services)",
    "Deutsche Bank (DBI)",
    "HSBC Software Development",
    "BNY Mellon Technology",
    "UBS Business Solutions",
    "Credit Suisse (UBS)",
    "Wells Fargo India",
    "Bank of America Continuum",
    "Standard Chartered GBS",
    "NatWest Group",
    "Fidelity Investments",
    "BlackRock",
    "Bajaj Finserv / Bajaj Finance",
    "HDFC Bank Digital Factory",
    "ICICI Bank Tech",
    // Core Engineering & Enterprise GCCs
    "Siemens Technology India",
    "Bosch Global Software Technologies",
    "Cummins India",
    "John Deere Technology Center",
    "Honeywell Technology Solutions",
    "Philips Innovation Campus",
    "GE Vernova / GE HealthCare",
    "Schneider Electric",
    "Mercedes-Benz Research & Development",
    "BMW TechWorks India",
    "Tata Elxsi",
    "L&T Technology Services (LTTS)",
    "Reliance Retail / JioMart",
    "Airtel Digital (Bharti Airtel)"
];

export const IT_SKILLS_CATEGORIES = {
    "Backend & Languages": [
        "Java",
        "Spring Boot",
        "Spring MVC",
        "Spring Security",
        "Hibernate / JPA",
        "Microservices",
        "Python",
        "Django",
        "FastAPI",
        "Flask",
        "Node.js",
        "Express.js",
        "NestJS",
        "C#",
        ".NET Core",
        "ASP.NET Web API",
        "Go (Golang)",
        "C++",
        "C Programming",
        "Rust",
        "PHP",
        "Laravel",
        "Ruby on Rails",
        "Scala",
        "Kotlin",
        "GraphQL",
        "RESTful APIs",
        "gRPC",
        "WebSockets",
        "Multithreading"
    ],
    "Frontend & UI": [
        "React.js",
        "Next.js",
        "Angular",
        "Vue.js",
        "JavaScript (ES6+)",
        "TypeScript",
        "HTML5",
        "CSS3",
        "Tailwind CSS",
        "Bootstrap",
        "Redux Toolkit",
        "Zustand",
        "Material UI (MUI)",
        "Shadcn UI",
        "SASS / SCSS",
        "Webpack / Vite",
        "Three.js",
        "Figma",
        "Responsive Web Design",
        "Web Accessibility (a11y)"
    ],
    "Databases & Caching": [
        "MySQL",
        "PostgreSQL",
        "Oracle SQL / PL-SQL",
        "Microsoft SQL Server",
        "MongoDB",
        "Redis",
        "Elasticsearch",
        "Cassandra",
        "DynamoDB",
        "Firebase / Firestore",
        "Supabase",
        "Neo4j",
        "SQLite",
        "MariaDB"
    ],
    "Cloud, DevOps & Infra": [
        "AWS (Amazon Web Services)",
        "Microsoft Azure",
        "Google Cloud Platform (GCP)",
        "Docker",
        "Kubernetes (K8s)",
        "Terraform",
        "Ansible",
        "Jenkins",
        "GitHub Actions",
        "GitLab CI/CD",
        "Linux / Unix Shell Scripting",
        "Nginx",
        "Apache Kafka",
        "RabbitMQ",
        "Prometheus & Grafana",
        "ELK Stack",
        "Helm",
        "ArgoCD",
        "Serverless / AWS Lambda"
    ],
    "AI, Data Science & Analytics": [
        "Machine Learning",
        "Deep Learning",
        "Generative AI & LLMs",
        "LangChain / LlamaIndex",
        "OpenAI / Gemini API",
        "Natural Language Processing (NLP)",
        "Computer Vision",
        "PyTorch",
        "TensorFlow",
        "Scikit-Learn",
        "Pandas & NumPy",
        "Data Science",
        "Data Engineering",
        "Apache Spark / PySpark",
        "Hadoop",
        "Airflow",
        "Snowflake",
        "Databricks",
        "Power BI",
        "Tableau",
        "Advanced Excel"
    ],
    "Mobile, QA & Core CS": [
        "React Native",
        "Flutter",
        "Android Development (Kotlin/Java)",
        "iOS Development (Swift)",
        "Selenium WebDriver",
        "Playwright",
        "Cypress",
        "Appium",
        "Postman API Testing",
        "JUnit & Mockito",
        "Jest",
        "JMeter Performance Testing",
        "Manual & Automation Testing",
        "Data Structures & Algorithms (DSA)",
        "Object-Oriented Programming (OOP)",
        "System Design (LLD / HLD)",
        "Git & GitHub",
        "Agile / Scrum",
        "Jira",
        "Cyber Security / OWASP",
        "OAuth2 & JWT"
    ]
};

export const ALL_IT_SKILLS = Object.values(IT_SKILLS_CATEGORIES).flat();

export const IT_DESIGNATIONS = [
    "Software Engineer",
    "Associate Software Engineer",
    "Graduate Engineer Trainee (GET)",
    "Software Developer",
    "Senior Software Engineer",
    "Full Stack Developer",
    "Java Full Stack Developer",
    "MERN Stack Developer",
    "Backend Developer",
    "Frontend Developer",
    "Java Developer",
    "Spring Boot Developer",
    "React.js Developer",
    "Angular Developer",
    "Python Developer",
    "Node.js Developer",
    ".NET Developer",
    "Golang Developer",
    "DevOps Engineer",
    "Cloud Engineer (AWS / Azure / GCP)",
    "Site Reliability Engineer (SRE)",
    "Data Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "AI / GenAI Engineer",
    "Data Analyst",
    "Business Intelligence (BI) Developer",
    "QA Automation Engineer",
    "SDET (Software Development Engineer in Test)",
    "Manual & Functional QA Engineer",
    "Performance Test Engineer",
    "Android Developer",
    "iOS Developer",
    "Flutter / React Native Developer",
    "UI/UX Designer",
    "Product Designer",
    "Product Manager",
    "Associate Product Manager",
    "Business Analyst",
    "Database Administrator (DBA)",
    "Cyber Security Engineer",
    "System Administrator / Network Engineer",
    "Technical Support / Application Support Engineer",
    "Technical Lead",
    "Module Lead",
    "Software Architect",
    "Solution Architect",
    "Engineering Manager",
    "Software Engineering Intern",
    "Data Science Intern"
];

export const IT_INDUSTRIES = [
    "IT Services & Consulting",
    "Software Product",
    "FinTech / Financial Services",
    "Banking & Capital Markets (BFSI)",
    "E-Commerce & Consumer Internet",
    "Cloud Computing & SaaS",
    "Artificial Intelligence & Data Analytics",
    "Healthcare IT & MedTech",
    "EdTech & E-Learning",
    "Telecom & ISP",
    "Automotive & Mobility Tech",
    "Cyber Security",
    "Gaming & Digital Media",
    "Manufacturing & Enterprise ERP",
    "Management Consulting"
];

export const IT_DEPARTMENTS = [
    "Engineering - Software & QA",
    "Data Science & Machine Learning",
    "DevOps, Cloud & Infrastructure",
    "IT & Information Security",
    "Product Management",
    "UI / UX & Product Design",
    "Quality Assurance & Testing",
    "DBA & Data Warehousing",
    "Enterprise ERP & CRM Consulting",
    "Technical Support & Operations",
    "Research & Development (R&D)"
];

export const ROLE_CATEGORIES = [
    "Software Development",
    "Quality Assurance and Testing",
    "DevOps / Cloud Infrastructure",
    "DBA / Data warehousing",
    "Business Intelligence & Analytics",
    "AI / Machine Learning",
    "UI / UX Design",
    "Enterprise & Solution Architecture",
    "Product Management",
    "IT Security / Cyber Security",
    "IT Support / System Administration",
    "Internship / Trainee"
];

export const NOTICE_PERIOD_OPTIONS = [
    "Immediate / Serving Notice",
    "15 Days or less",
    "30 Days (1 Month)",
    "45 Days",
    "60 Days (2 Months)",
    "90 Days (3 Months)"
];

export const EMPLOYMENT_TYPES = [
    { value: "FULL_TIME", label: "Full-Time (Permanent)" },
    { value: "INTERNSHIP", label: "Internship / Trainee" },
    { value: "CONTRACT", label: "Contract / Consultant" },
    { value: "FREELANCE", label: "Freelance / Part-Time" }
];

export const WORK_MODE_OPTIONS = [
    "Hybrid",
    "On-site / Office",
    "Remote / Work from Home",
    "Flexible (Any)"
];

export const SHIFT_OPTIONS = [
    "Day Shift",
    "Flexible / Rotational",
    "Night Shift",
    "UK / US Overlap Shift"
];

export const DESIRED_JOB_TYPES = [
    "Permanent",
    "Contractual",
    "Both (Permanent & Contractual)"
];

export const DESIRED_EMPLOYMENT_TYPES = [
    "Full Time",
    "Full Time & Internship",
    "Part Time / Freelance"
];

export const MARITAL_STATUS_OPTIONS = [
    "Single / Unmarried",
    "Married",
    "Prefer not to say"
];

export const INDIAN_LANGUAGES = [
    "English",
    "Hindi",
    "Marathi",
    "Tamil",
    "Telugu",
    "Kannada",
    "Malayalam",
    "Gujarati",
    "Bengali",
    "Punjabi",
    "Odia",
    "Assamese",
    "Urdu",
    "Sanskrit",
    "German",
    "Japanese",
    "French",
    "Spanish"
];

export const INDIAN_COLLEGES_AND_UNIVERSITIES = [
    "Savitribai Phule Pune University (SPPU)",
    "University of Mumbai",
    "COEP Technological University, Pune",
    "Pune Institute of Computer Technology (PICT), Pune",
    "Vishwakarma Institute of Technology (VIT), Pune",
    "MIT World Peace University (MIT-WPU), Pune",
    "Cummins College of Engineering for Women, Pune",
    "PCCOE (Pimpri Chinchwad College of Engineering), Pune",
    "Sinhgad College of Engineering, Pune",
    "DY Patil College of Engineering, Pune",
    "Symbiosis Institute of Technology (SIT), Pune",
    "VJTI (Veermata Jijabai Technological Institute), Mumbai",
    "Sardar Patel Institute of Technology (SPIT), Mumbai",
    "DJ Sanghvi College of Engineering, Mumbai",
    "KJ Somaiya College of Engineering, Mumbai",
    "Walchand College of Engineering, Sangli",
    "Government College of Engineering, Karad",
    "Government College of Engineering, Chhatrapati Sambhajinagar",
    "VNIT (Visvesvaraya National Institute of Technology), Nagpur",
    "Shri Ramdeobaba College of Engineering (RCOEM), Nagpur",
    "YCCE (Yeshwantrao Chavan College of Engineering), Nagpur",
    "KK Wagh Institute of Engineering Education, Nashik",
    "Shivaji University, Kolhapur",
    "RTM Nagpur University",
    "Dr. Babasaheb Ambedkar Technological University (DBATU), Lonere",
    "IIT Bombay",
    "IIT Delhi",
    "IIT Madras",
    "IIT Kanpur",
    "IIT Kharagpur",
    "IIT Roorkee",
    "IIT Hyderabad",
    "BITS Pilani",
    "IIIT Hyderabad",
    "IIIT Bangalore",
    "IIIT Pune",
    "IIIT Nagpur",
    "NIT Trichy",
    "NIT Surathkal (NITK)",
    "NIT Warangal",
    "VIT Vellore",
    "SRM Institute of Science and Technology",
    "Manipal Institute of Technology (MIT)",
    "RV College of Engineering (RVCE), Bengaluru",
    "BMS College of Engineering, Bengaluru",
    "PES University, Bengaluru",
    "Visvesvaraya Technological University (VTU), Belagavi",
    "Anna University, Chennai",
    "JNTU Hyderabad",
    "Delhi Technological University (DTU)",
    "NSUT Delhi",
    "Jadavpur University, Kolkata",
    "Gujarat Technological University (GTU)"
];
